source :rubygems
gem "sinatra"
gem 'sinatra-flash'
gem 'pony'
gem 'coffee-script'
gem "slim"
gem "sass"
gem "dm-core"
gem "dm-migrations"
gem "thin"
gem "pg", :group => :production
gem "dm-postgres-adapter", :group => :production
gem "dm-sqlite-adapter", :group => :development